apiVersion: v2
name: helmcoins
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: generic
    version: "*"
    alias: hasher
  - name: generic
    version: "*"
    alias: redis
    condition: redis.useInternal
  - name: redis
    alias: redis-external
    repository: https://charts.bitnami.com/bitnami
    version: ">=19, <20" #19.5.0
    condition: redis.useExternal
  - name: generic
    version: "*"
    alias: rng
  - name: generic
    version: "*"
    alias: webui
  - name: generic
    version: "*"
    alias: worker