redis:
  image:
    repository: redis
    tag: 7.0.15-alpine
  livenessProbe: null
  readinessProbe: null
  service:
    port: 6379

webui:
  service:
    type: NodePort

worker:
  livenessProbe: null
  readinessProbe: null
  service: false