{{ if .Values.service }}

{{- $targetPort := .Values.service.targetPort | default .Values.service.port -}}
{{- $port := .Values.service.port -}}
{{- $namedPort := $port | default $targetPort | toString -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ $port }}
      targetPort: {{ $targetPort }}
      protocol: TCP
      name: {{ include "portName" $targetPort }}
  selector:
    {{- include "generic.selectorLabels" . | nindent 4 }}
{{ end }}