{{ if .Values.redis.useExternal }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  externalName: redis-master.{{ .Release.Namespace }}.svc.cluster.local
  selector:
    app: redis
  type: ExternalName
{{ end }}
{{ if and .Values.redis.useExternal .Values.redis.useInternal }}
--- # In order to get another separated ressource 
kind: Error
apiVersion: "Cannot have both redis.useInternal and redis.useExternal set at the same time!"
{{ end }}